### ISSUE TITLE
Idea for multiple columns

### ISSUE THREAD

**Issue by mathieugouin** [melodiegagnon1/melodiegagnon1.github.io#27]
```html
<div class="container">
  <div class="left-content">Left Content</div>
  <div class="right-content">Right Content</div>
</div>
```

```css
/* Default styles for larger screens */
.container {
  display: flex;
}

.left-content,
.right-content {
  flex: 1;
}

/* Media query for smaller screens */
@media screen and (max-width: 768px) {
  .container {
    flex-direction: column;
  }
}
```
